# Fayl nomi: .github/workflows/render-report.yml

name: Render and Deploy Quarto Report

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fayllarni ko'chirib olish (Checkout)
        uses: actions/checkout@v4

      - name: Quarto va R'ni sozlash
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'
      - uses: quarto-dev/quarto-actions/setup@v2

      # --- YANGILANGAN QADAM ---
      - name: Tizim kutubxonalarini o'rnatish
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev libproj-dev libgeos-dev libudunits2-dev
      # ---------------------------

      - name: R paketlarini o'rnatish
        run: |
          install.packages(c('httr', 'jsonlite', 'dplyr', 'ggplot2', 'DT', 'lubridate', 'leaflet', 'tidyr', 'gt', 'terra', 'units'))
        shell: Rscript {0}

      - name: Hisobotni render qilish (HTML yaratish)
        run: |
          quarto render index.qmd --to html
        shell: bash

      - name: Natijani GitHub Pages uchun tayyorlash (Upload Artifact)
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Veb-sahifani nashr qilish (Deploy to Pages)
        id: deployment
        uses: actions/deploy-pages@v4
